trigger:
- none
parameters:
  - name: version
    type: string 
    default: "1.0.0"
  - name: ENV
    type: string 
    default: "dev"
    values:
      - dev
      - prod 
pool:
  name: "MCDAI-B1-POOL"
  vmImage: "workstation"

steps:
- task: UniversalPackages@1
  inputs:
    command: 'download'
    feed: 'mcdaib1/myapp-artifacts'
    packageName: 'javaspringboot'
    packageVersion: '${{ parameters.version }}'
    directory: '$(System.DefaultWorkingDirectory)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      ls -l 

- task: Bash@3
  displayName: "change key permissions"
  inputs:
    targetType: 'inline'
    script: 'chmod 600 mykey.pem'
    failOnStderr: true

- task: Bash@3
  displayName: "Execute ansible playbook"
  inputs:
    targetType: 'inline'
    script: 'ansible-playbook -i hosts java-cd.yaml -e env=${{ parameters.ENV}} -v'
    failOnStderr: true
